-- MySQL Script generated by MySQL Workbench
-- Do 11 Nov 2021 23:09:57 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema soundboard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soundboard
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `soundboard` DEFAULT CHARACTER SET utf8 ;
USE `soundboard` ;

-- -----------------------------------------------------
-- Table `soundboard`.`profil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soundboard`.`profil` ;

CREATE TABLE IF NOT EXISTS `soundboard`.`profil` (
  `profil_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `profile_imag` VARCHAR(255) NULL,
  `sounds` VARCHAR(45) NULL,
  PRIMARY KEY (`profil_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_german2_ci;


-- -----------------------------------------------------
-- Table `soundboard`.`sound`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soundboard`.`sound` ;

CREATE TABLE IF NOT EXISTS `soundboard`.`sound` (
  `sounds_id` INT NOT NULL AUTO_INCREMENT,
  `sound_path` VARCHAR(255) NULL,
  `sound_name` VARCHAR(45) NULL,
  `sound_img` VARCHAR(255) NULL,
  `profil_id` INT NOT NULL,
  PRIMARY KEY (`sounds_id`),
  INDEX `fk_sound_profil_idx` (`profil_id` ASC) VISIBLE,
  CONSTRAINT `fk_sound_profil`
    FOREIGN KEY (`profil_id`)
    REFERENCES `soundboard`.`profil` (`profil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundboard`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soundboard`.`category` ;

CREATE TABLE IF NOT EXISTS `soundboard`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soundboard`.`category_sound`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soundboard`.`category_sound` ;

CREATE TABLE IF NOT EXISTS `soundboard`.`category_sound` (
  `category_category_id` INT NOT NULL,
  `sound_sounds_id` INT NOT NULL,
  PRIMARY KEY (`category_category_id`, `sound_sounds_id`),
  INDEX `fk_category_has_sound_sound1_idx` (`sound_sounds_id` ASC) VISIBLE,
  INDEX `fk_category_has_sound_category1_idx` (`category_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_has_sound_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `soundboard`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_sound_sound1`
    FOREIGN KEY (`sound_sounds_id`)
    REFERENCES `soundboard`.`sound` (`sounds_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
